- name: Doxygen Deploy Action
        uses: JustEnoughMod/DoxygenDeployAction@1.0.1
        with:
          # A GitHub token for pushing to the repo. 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Branch name for pushing GitHub pages files
          branch: gh-pages
          # Folder where Doxygen will generate the HTML build files
          folder: html
          # Path of the Doxygen configuration file
          config_file: Doxyfile
