name: Deploy Doxygen via Action

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Doxygen Deploy Action
        uses: JustEnoughMod/DoxygenDeployAction@1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: html
          config_file: Doxyfile
